[package]

name = "crate-label"
version = "0.0.1"
authors = ["softprops <d.tangren@gmail.com>"]

[dependencies]
hyper = "0.3.13"
rustc-serialize = "0.3.12"
iron = "0.1.16"
handlebars-iron = "0.6.2"
router = "0.0.10"
mime = "0.0.10"