[package]

name = "crate-label"
version = "0.0.1"
authors = ["softprops <d.tangren@gmail.com>"]

[dependencies]
hyper = "0.3.0"
rustc-serialize = "0.3.1"
iron = "0.1.11"
handlebars-iron = "0.5.2"
router = "0.0.9"
mime = "0.0.10"